### ISSUE TITLE
whatsapp block

### ISSUE THREAD

**Issue by OliverHering** [jbollacke/whatsapp-photo-frame#1]
Hi,

I used your code, and my phone-number got blocked by whatsapp after one day.
Is your photo-frame still working? -If yes, how did you manage to do this? Are you still using the auto response messages?

Cheers,
Mickey

**Comment by jbollacke** [comment]
Hi, sorry to hear that your number got blocked.
My installation based on the master branch is still working w/ auto response messages.

Which version of yowsup ur using?

Currently I think its best to use my [fork](https://github.com/jbollacke/yowsup) of yowsup. Basically it is the master branch from tgalal/yowsup with PR [#1713](https://github.com/tgalal/yowsup/pull/1713) merged to fix encrypted image downloads.

**Comment by OliverHering** [comment]
Yowsup v2.5.0 with your pull request #1713

**Comment by jbollacke** [comment]
Well, should work then.

You might want to try w/o that auto response message once ur number is not banned anymore.

How many photos were received before the number got banned? I never received more than approx. 8 photos per hour.

**Comment by OliverHering** [comment]
16 images in about 3h, while i was testing the setup.

My next idea would be to use an old phone, install whatsapp and sync the whatsapp image folder with BitTorrent Sync to the Raspberry-Pi.
But it's slow and i always have to have the phone switched on.

**Comment by jbollacke** [comment]
Yeah. An old phone was my fallback plan if I did not manage to fix retrieval of encrypted Images.

I would have connected it using an USB cable and schedule an adb pull w/ cron though.

Or https://github.com/google/adb-sync

**Comment by OliverHering** [comment]
Ok, maybe I'll try that, thanks.

**Comment by AppMessenger** [comment]
Hi, how can I contact you for commercial offers, need help.
